### ISSUE TITLE
Error Code 05

### ISSUE THREAD

**Issue by cods4** [byte4geek/SEPLOS_MQTT#10]
When making the changes suggested in https://diysolarforum.com/threads/simple-seplos-bms-protocol-decode-bash-script.34993/page-2#post-677063 you missed one.
Line 130 in query_seplos_ha.sh should be:
`echo -ne "$SEND" >$DEV`

instead of:
`echo -e "$SEND" >$DEV`

**Comment by byte4geek** [comment]
I'm happy you solved your issue, only one think, on my raspberry the script works well whit both options.

**Comment by byte4geek** [comment]
https://github.com/byte4geek/SEPLOS_MQTT/issues/7

**Comment by byte4geek** [comment]
duplicated -->  https://github.com/byte4geek/SEPLOS_MQTT/issues/7
