### ISSUE TITLE
Script with Seplos 3.0

### ISSUE THREAD

**Issue by otello86** [byte4geek/SEPLOS_MQTT#11]
Hi,
Do you know if this script is working with the version 3.0 of the Seplos BMS ?
I bought a battery with this version of bms and for the moment i got directly this error : "Failed to read start of input char (~), read ""
I have no line with "Sending...."
I check the rs485 connector and it works fine the seplos Monitor tool

**Comment by byte4geek** [comment]
Sorry but i do not have the hardware 3.0 i can't help you, just in case you can ask to the forum where the author wrote the intial script query_seplos.sh https://diysolarforum.com/threads/simple-seplos-bms-protocol-decode-bash-script.34993/page-2#post-677063

EDIT
I saw you already asked it on the foum

**Comment by otello86** [comment]
Hi, which information do you need to do this ? i could send them to you ?

**Comment by byte4geek** [comment]
Without a board to test it is impossible for me to do the script for the version 3
