### ISSUE TITLE
Problem with shell command

### ISSUE THREAD

**Issue by jannixxx1564** [byte4geek/SEPLOS_MQTT#15]
Hi byte4geek,

unfortunately I need your support with the SEPLOS_MQTT project. 
At the following command line I didn't know exactly what to do and where:
"create a shell command in HA:
seplos_query: ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no root@<YOUR HA IP> "cd /share/SEPLOS_MQTT;nohup /share/SEPLOS_MQTT/run_bms_query_ha.sh &""

can you help me?

best regards
Jan

**Comment by byte4geek** [comment]
Sorry but i can't support on the installation.
