### ISSUE TITLE
Error Code 05

### ISSUE THREAD

**Issue by tim-mills** [byte4geek/SEPLOS_MQTT#2]
I’m desperate for this to work, just keep getting an error code 5, anything I can try?

**Comment by byte4geek** [comment]
did you try to run it manually?
To test if the communication is working try to run `~/SEPLOS_MQTT/query_seplos_ha.sh 4201`

**Comment by tim-mills** [comment]
Thanks for getting back to me. That's what I've been trying, Just comes straight back with Error Code 05. Just struggling to see how I can debug the issue, so any pointers are welcome. 

![Capture](https://user-images.githubusercontent.com/8787873/204237563-18706b0a-498a-4d93-a265-d28bd1ed2b1c.PNG)
![Capture1](https://user-images.githubusercontent.com/8787873/204237569-49e9b5b3-a9e4-419c-bf4f-0f823921b82d.PNG)

**Comment by byte4geek** [comment]
check if you have address 1 (battery number 1) in the battery configuration

**Comment by tim-mills** [comment]
Battery configuration, as in via the Seplos software?

**Comment by tim-mills** [comment]
Just to confirm, all my DIP switches are OFF, which I think means it's set to single pack. I've tried setting DIP 1 to ON, which means it's 1st pack, although this didn't seem to work and also meant my Solis Inverter got a CAN fail.

**Comment by byte4geek** [comment]
i seen you did ask for this issue on the original discussion of the original script creator:
https://diysolarforum.com/threads/simple-seplos-bms-protocol-decode-bash-script.34993/
wait for the answare in the forum i don't know error 5 says.

**Comment by tim-mills** [comment]
No worries - I've just noticed you just put a wrapper around the script. I'll wait and see if they get back to me on there, I wonder if there's been a shift in the different versions of the BMS.

**Comment by roverga** [comment]
Great project, but I have the same problem: Error 5!

**Comment by byte4geek** [comment]
> Great project, but I have the same problem: Error 5!

Sorry but regarding this error, you must ask to the author of the original script as specified 2 post up.

**Comment by roverga** [comment]
I finally find a solution for the "Error Code 05" that works for me. 

I write my solution on the original discussion:
[https://diysolarforum.com/threads/simple-seplos-bms-protocol-decode-bash-script.34993/post-677063](https://diysolarforum.com/threads/simple-seplos-bms-protocol-decode-bash-script.34993/post-677063)
