### ISSUE TITLE
Potential to use over network via RS485 to TCP/IP Converter

### ISSUE THREAD

**Issue by iandarbey** [byte4geek/SEPLOS_MQTT#6]
More of a feature request.....

Would it be possible (forgive me if it already is possible and I've misread the docs) to manage this via something like the waveshare below?

Waveshare Industrial Serial Server RS485 to RJ45 Ethernet TCP/IP to Serial Module Support Rail-Mount Modbus Gateway https://amzn.eu/d/aFbXNxA

I'll have network in my planned inverter and battery location (shed) but my pi running HA will be quite far away (in the house) so planned to have one of these units for talking to inverter anyway so another setup to talk to the seplos would be great.

**Comment by byte4geek** [comment]
you just have to try it, the script doesn't have to do different things, you just have to pay attention to how the serial device will be once configured on your raspberry example: /dev/netadapter485
