### ISSUE TITLE
Error Code 05

### ISSUE THREAD

**Issue by Thermicblowfish** [byte4geek/SEPLOS_MQTT#7]
Hi 

I am just getting error code 05 when trying to run the script - I believe this is a BMS read error?

**Comment by Thermicblowfish** [comment]
Hi - resolved the error code 05 - there was a spelling error in the script. (-e near the end should be -ne), can now test it manually and pull in the data but when i run the run_bms_query.sh I get a 'Unable to connect (lookup error)

**Comment by alfagero** [comment]
hi! i have also the error code 05. Can you tell me the line and the script name ?

**Comment by alfagero** [comment]
ok i found it: in query_seplos_ha.sh line 130

**Comment by byte4geek** [comment]
Fixed, added -ne to line 130
