### ISSUE TITLE
Esp32/8266

### ISSUE THREAD

**Issue by JoeGhost-22** [byte4geek/SEPLOS_MQTT#8]
Hi, I dont know anything about codeing, but is there any way to run your code on a esp32 or 8266. ? That would help me a lot, cause I dont want to spend a lot of money for a raspi to monitor the battery pack.  I run the other code from github, but Im not satisfied with it. 
regards
Joerg.

**Comment by byte4geek** [comment]
Sorry this code is not for esp32, but you can run this on an old eeepc with debian OS you can buy an old eeepc for a little money

**Comment by JoeGhost-22** [comment]
Thank you for the Info. Two more questions. Can it monitor multiple packs? Are u still working on it.? I've 2 packs at the moment and plan to add a third. Do I need a  eepc for every pack?

Thank you and have a nice weekend
Best regards
Joerg

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JoeGhost-22** [comment]
Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by byte4geek** [comment]
Sorry i'm not working for 2 packs or more, but for the simple way you can use 2 rs485 adapter and run 2 script in parallel by changing the directory script name and changing the /dev/ttyUSB0 name in the /dev/ttyUSB1, but after this change the id_prefix=364715398511 in id_prefix=364715398512 with another number and create all entity in HA with the prefix 00 and 01 and nn

for example:

mqtt:
  sensor:

    - name: "BMS01 Cell 01"  <--- changed
      state_topic: "homeassistant/sensor/seplos_364715398512"  <--- changed
      value_template: '{{ value_json["cell01"] }}'
      unit_of_measurement: "mV"
      unique_id: "seplos_cell01_364715398512"  <--- changed
      icon: mdi:car-battery
      device_class: voltage
      expire_after: 600
